drop table if exists brand;
drop table if exists collection;
drop table if exists collection_skeins;
drop table if exists skein;
drop table if exists skein_possession;
drop table if exists usage_config;
drop table if exists usage_config_value;
drop table if exists user_info;
drop table if exists user_collection;
